### PR TITLE
Code improvements, compatibility with WBMQTTImport, correct handling of "/" in the title

### PR DESCRIPTION
**Pull request by PoltoS**
- Moved some vars and prototypes to static variables.
- Removed wrong С and replaced with C
- Create prototypes on String only if not yet defined (to allow future ES6 native support)
- Remove "/" from device title (topic name) not to mangle the structure
- Skip devices created by WBMQTTImport module (to prevent recursive device creation)
- Support of switchControl
- Added groupByDevices flag
- Handle empty/null values
- Automatic upload on release or on GitHub Action run
- Version bump

### CODE REVIEW

**Comment by PoltoS** [comment]
@ekateluv Please review this PR

Easier to review each commit - each small change is documented.

**Review by ekateluv — APPROVED** [review]

**Comment by webconn** [comment]
can we merge this? will it break something after 2 months? @PoltoS @ekateluv

**Comment by PoltoS** [comment]
We use this version in the current version. During the build it is downloaded from our store (http://developer.z-wave.me/?uri=public#/web/apps/544) and compiled based on sources from https://github.com/Z-Wave-Me/WBMQTTNative (auto-uploaded via the GitHub actions)

**Comment by PoltoS** [comment]
I propose to merge it

**Pull request merged**
